name = "trueschools"
compatibility_date = "2024-12-01"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "trueschools-db"
database_id = "e458b930-5925-41b1-9307-ebf6996e34ea"

[vars]
ENVIRONMENT = "production"

[dev]
port = 4321
